package com.mblog;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		System.out.println("'zhe这是里执行力:'addNewUser");
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		System.out.println("'name:'"+name);
		userRepository.save(n);
		return "Saved";
	}

	@PostMapping(path="/addJson") // Map ONLY POST Requests
	public @ResponseBody String addNewUserJson (@RequestBody User user) {
		userRepository.save(user);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

//	@GetMapping("/blogs")
//	public Result blogs(@RequestParam(defaultValue = "1") Integer pageNum) {
//		PageResult<BlogInfo> pageResult = blogService.getBlogInfoListByIsPublished(pageNum);
//		return Result.ok("请求成功", pageResult);
//	}
}
