package com.mblog.controller;

import com.mblog.model.Blog;
import com.mblog.model.Result;
import com.mblog.model.PageResult;
import com.mblog.service.BlogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController	// This means that this class is a Controller
public class BlogController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private BlogRepository blogRepository;
	@GetMapping(path="/getBlog")
	public Result findBlog(@RequestParam(value = "id",defaultValue = "0") Integer id) {
		Optional<Blog> blog =  blogRepository.findById(id);
		return Result.ok("请求成功", blog);
	}

	@GetMapping(path="/getBlogByTitle")
	public @ResponseBody Blog getBlog(@RequestParam(value = "title") String title) {
		return blogRepository.getByTitle(title).orElse(null);
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Blog> getAll() {
		return blogRepository.findAll();
	}

	@GetMapping(path="/blogs")
	public Result getAllPage(@RequestParam(value = "page") Integer page) {
		Pageable request = PageRequest.of(page-1, 10);
		Integer count = blogRepository.findCount();
		PageResult<Blog> pageResult = new PageResult<>(count, blogRepository.findCurPage(request));
        return Result.ok("请求成功", pageResult);
	}

	@PostMapping(path="/admin/addBlog")
	public Result addBlog (@RequestBody Blog blog) {
		blogRepository.save(blog);
		return Result.ok("添加成功");
	}

	@PostMapping(path="/admin/delById")
	public Result delById (Integer id) {
		blogRepository.deleteById(id);
		return Result.ok("删除成功");
	}

	@ResponseBody
	@GetMapping("search")
	public List<Blog> search(String keyword){
		return blogRepository.findAllByTitleContains(keyword);
	}
}
