package com.mblog.controller;
import com.mblog.model.Blog;
import com.mblog.service.BlogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class BlogController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private BlogRepository blogRepository;
	@GetMapping(path="/blog")
	public @ResponseBody Blog findBlog(@RequestParam(value = "id",defaultValue = "") String id) {
		// This returns a JSON or XML with the users
		return getBlog(id);
	}

	@GetMapping(path="/getBlogByTitle")
	public @ResponseBody Blog getBlog(@RequestParam(value = "title") String title) {
		// This returns a JSON or XML with the users
		return blogRepository.getByTitle(title).orElse(null);
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Blog> getAllUsers() {
		// This returns a JSON or XML with the users
		return blogRepository.findAll();
	}

	@ResponseBody
	@GetMapping("search")
	public List<Blog> search(String keyword){
		return blogRepository.findAllByTitleContains(keyword);
	}
}
